Repository aliparlakci/bulk-downloader-for-reddit, pull requests merged in 2021-05, with the labels that each got.

#349 Fix xml archiver encoding bug
  bdfr/archiver.py
  tests/test_integration.py
Labels: bug

#391 Set file creation times to the post creation time
  bdfr/downloader.py
Labels: enhancement

#409 Adding info to threads and comments: distinguished, spoiler, pinned, locked
  bdfr/archive_entry/base_archive_entry.py
  bdfr/archive_entry/submission_archive_entry.py
  tests/archive_entry/test_comment_archive_entry.py
  tests/archive_entry/test_submission_archive_entry.py
Labels: feature

#417 Read files in chunks when calculating the existing hashes
  bdfr/downloader.py
Labels: bug
