Repository aliparlakci/bulk-downloader-for-reddit, pull requests merged in 2021-03, with the labels that each got.

#176 Added new --download-delay flag to allow throttling downloads
  script.py
  src/arguments.py
Labels: enhancement, v1

#215 Fix error "'NoneType' object is not iterable" (issue #214) and "InvalidSchema: No connection adapters were found" (issue #198)
  src/downloaders/Gallery.py
  src/searcher.py
Labels: v1

#225 Bug fix on deleted self posts
  bulkredditdownloader/site_downloaders/self_post.py
  bulkredditdownloader/tests/downloaders/test_self_post.py
Labels: bug, v2-beta

#229 Fix downloading .gifv instead of .mp4 (#228)
  bulkredditdownloader/site_downloaders/download_factory.py
  bulkredditdownloader/site_downloaders/imgur.py
  bulkredditdownloader/tests/downloaders/test_download_factory.py
  bulkredditdownloader/tests/downloaders/test_imgur.py
Labels: bug, v2-beta

#230 Send HTTP200 when oauth2 is successful
  bulkredditdownloader/oauth2.py
Labels: v2-beta

#237 Tweak regex to fix incorrect match
  bulkredditdownloader/site_downloaders/download_factory.py
  bulkredditdownloader/tests/downloaders/test_download_factory.py
Labels: bug, v2-beta

#227 File formatter bug fix
  bulkredditdownloader/file_name_formatter.py
  bulkredditdownloader/tests/test_file_name_formatter.py
Labels: bug, v2-beta

#239 test_download_factory.py: hardcode submission links
  bulkredditdownloader/tests/downloaders/test_download_factory.py
Labels: v2-beta
